//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<int> PlaceBirthId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Phone { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual PlaceBirth PlaceBirth { get; set; }
        public virtual User User { get; set; }
    }
}
